apiVersion: v1
kind: ConfigMap
metadata:
  name: rabbitmq-config
  namespace: fcg
data:
  rabbitmq.conf: |
    load_definitions = /etc/rabbitmq/definitions.json
  definitions.json: |
    {
      "rabbit_version": "3.13.0",
      "users": [
        {
          "name": "guest",
          "password_hash": "DCGILKCMPLvOIjX54EVjXBkcXE0sw8FwyPM46v/sGjml9nbb",
          "hashing_algorithm": "rabbit_password_hashing_sha256",
          "tags": ["administrator"]
        }
      ],
      "vhosts": [{ "name": "/" }],
      "permissions": [
        { "user": "guest", "vhost": "/", "configure": ".*", "write": ".*", "read": ".*" }
      ],
      "queues": [
        { "name": "welcome-email", "vhost": "/", "durable": true, "auto_delete": false, "arguments": {} },
        { "name": "purchase-confirmation", "vhost": "/", "durable": true, "auto_delete": false, "arguments": {} }
      ],
      "exchanges": [
        { "name": "Fcg.Contracts.Events:UserCreatedEvent", "vhost": "/", "type": "fanout", "durable": true, "auto_delete": false, "internal": false, "arguments": {} },
        { "name": "Fcg.Contracts.Events:PaymentProcessedEvent", "vhost": "/", "type": "fanout", "durable": true, "auto_delete": false, "internal": false, "arguments": {} },
        { "name": "welcome-email", "vhost": "/", "type": "fanout", "durable": true, "auto_delete": false, "internal": false, "arguments": {} },
        { "name": "purchase-confirmation", "vhost": "/", "type": "fanout", "durable": true, "auto_delete": false, "internal": false, "arguments": {} }
      ],
      "bindings": [
        { "source": "Fcg.Contracts.Events:UserCreatedEvent", "vhost": "/", "destination": "welcome-email", "destination_type": "exchange", "routing_key": "", "arguments": {} },
        { "source": "welcome-email", "vhost": "/", "destination": "welcome-email", "destination_type": "queue", "routing_key": "", "arguments": {} },
        { "source": "Fcg.Contracts.Events:PaymentProcessedEvent", "vhost": "/", "destination": "purchase-confirmation", "destination_type": "exchange", "routing_key": "", "arguments": {} },
        { "source": "purchase-confirmation", "vhost": "/", "destination": "purchase-confirmation", "destination_type": "queue", "routing_key": "", "arguments": {} }
      ],
      "policies": [],
      "parameters": [],
      "global_parameters": [],
      "topic_permissions": []
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq
  namespace: fcg
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
        - name: rabbitmq
          image: rabbitmq:3-management
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5672
              name: amqp
            - containerPort: 15672
              name: management
          volumeMounts:
            - name: rabbitmq-conf
              mountPath: /etc/rabbitmq/rabbitmq.conf
              subPath: rabbitmq.conf
            - name: rabbitmq-definitions
              mountPath: /etc/rabbitmq/definitions.json
              subPath: definitions.json
      volumes:
        - name: rabbitmq-conf
          configMap:
            name: rabbitmq-config
            items:
              - key: rabbitmq.conf
                path: rabbitmq.conf
        - name: rabbitmq-definitions
          configMap:
            name: rabbitmq-config
            items:
              - key: definitions.json
                path: definitions.json
---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  namespace: fcg
spec:
  selector:
    app: rabbitmq
  ports:
    - name: amqp
      port: 5672
      targetPort: 5672
    - name: management
      port: 15672
      targetPort: 15672
