apiVersion: v1
kind: Secret
metadata:
  name: kong-config
  namespace: fcg
type: Opaque
stringData:
  kong.yml: |
    _format_version: "3.0"
    services:
      - name: users-api
        url: http://users-api
        routes:
          - name: auth-route
            paths: ["/api/Auth"]
            strip_path: false
          - name: user-register-route
            paths: ["/api/User"]
            methods: ["POST"]
            strip_path: false
          - name: user-protected-route
            paths: ["/api/User"]
            methods: ["GET", "PUT", "DELETE", "PATCH"]
            strip_path: false
            plugins:
              - name: jwt
                config:
                  claims_to_verify: ["exp"]
      - name: catalog-api
        url: http://catalog-api
        routes:
          - name: catalog-route
            paths: ["/api/Game", "/api/purchases", "/api/Review"]
            strip_path: false
            plugins:
              - name: jwt
                config:
                  claims_to_verify: ["exp"]
    consumers:
      - username: fcg-app
        jwt_secrets:
          - key: "FiapCloudGames"
            algorithm: HS256
            secret: "fcg-fase2-shared-secret-key-please-change-32+chars"
