apiVersion: v1
kind: ConfigMap
metadata:
  name: catalog-config
  namespace: fcg
data:
  RabbitMq__Host: "rabbitmq"
  JwtSettings__Issuer: "FiapCloudGames"
  JwtSettings__Audience: "FiapCloudGames.Client"
  MongoSettings__ConnectionString: "mongodb://mongodb:27017"
  MongoSettings__Database: "fcg_catalog"
  RedisSettings__ConnectionString: "redis:6379"
